- name: Automatic Semantic Versioning
- id: next_version
  uses: zwaldowski/semver-release-action@v1
    with:
      dry_run: true
      bump: ${{ … }}
      github_token: ${{ secrets.YOUR_GITHUB_TOKEN }}
// Do something to modify the repo using `${{ steps.next_version.outputs.version }}`.
- run: echo "${{ steps.next_version.outputs.version }}"
- run: |
    git add .
    git commit -m "Bump version"
    git push
    echo ::set-output name=sha::$(git rev-parse HEAD)
- uses: zwaldowski/semver-release-action@v1
  with:
    github_token: ${{ secrets.YOUR_GITHUB_TOKEN }}
    sha: ${{ steps.git_commit.outputs.sha }}
